#!/bin/env python
import re
import csv
otr="<tr>"
ctr="<tr>"
otd="<td>"
ctd="</td>"
tblo= "<table>"
tblc= "</table>"

print tblo

print otr+otd+"Neigbor"+ctd+ \
      otd+"ASN"+ctd+\
      otd+"Flaps"+ctd+\
      otd+"uptime"+ctd+\
      otd+"status1"+ctd+\
      otd+"status1"+ctd+\
      otd+"status1"+ctd+\
      otd+"status1"+ctd+\
      otd+"status1"+ctd+ctr 


file = open('mylog')
for line in file:
        string = line.replace("\n","")
        if (re.match('[\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}]',string)):
                bgp_session = string.replace("|", " ")
                print otr+otd+bgp_session.split()[0]+ctd+ \
                      otd+bgp_session.split()[1]+ctd+ \
                      otd+bgp_session.split()[2]+ctd+ \
                      otd+bgp_session.split()[3]+ctd+ \
                      otd+bgp_session.split()[4]+ctd+ \
                      otd+bgp_session.split()[5]+ctd+ \
                      otd+bgp_session.split()[6]+ctd+ \
                      otd+bgp_session.split()[7]+ctd+ \
                      otd+bgp_session.split()[8]+ctd+ctr\

print tblc
